language: csharp
sudo: false  # use the new container-based Travis infrastructure 
dist: trusty

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main'
      key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x417A0893'
    packages:
      - dotnet-dev-1.0.1

script: 
  - ./build.sh All

